language: java

 before_script:  
  - echo -e "Host 154.5.3.58\n\tHostName 154.5.3.58\n\tUser Eric\n\tIdentityFile ~/.ssh/id_rsa\n" >> ~/.ssh/config
  
script:
  - echo -n $id_rsa >> ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host 154.5.3.58\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh Eric@154.5.3.58
  - docker start oracletest-ee
  - ant test
